# Generated by Django 5.0.3 on 2024-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_alter_flat_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
