# Generated by Django 5.0.3 on 2024-10-27 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_alter_flat_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
