# Generated by Django 5.0.3 on 2024-10-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_alter_flat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='condition',
            field=models.CharField(choices=[('Fully Renovated', 'Fully Renovated'), ('Basic Renovation', 'Basic Renovation'), ('Not Renovated', 'Not Renovated')], max_length=99),
        ),
    ]
